[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "holochat"
version = "0.1.1"
description = "A tools for facilitating communication between multiple computers during experiments."
authors = [
    {name = "Will Hendricks", email = "hendricksw@gmail.com"}
]
readme = "README.md"
license = {file = "LICENSE"}
dependencies = [
    "fastapi",
    "pydantic",
    "uvicorn[standard]"
]
requires-python = ">=3.10"

[project.optional-dependencies]
dev = [
    "rich",
    "httpx",
    "pytest",
    "pyfakefs"
]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]